dataDir: /home/nonroot/store
luceneDir: /home/nonroot/lucene
sitePrefix: http://vocab.belgif.be/
overwrite: true

ontologies:
    downloadDir: /home/nonroot/download-ns
    importDir: /home/nonroot/import-onto

vocabularies:
    downloadDir: /home/nonroot/download-auth
    importDir: /home/nonroot/import-auth

shacls:
    downloadDir: /home/nonroot/download-shacl
    importDir: /home/nonroot/import-shacl

jsonldcontexts:
    downloadDir: /home/nonroot/download-ctx
    importDir: /home/nonroot/import-ctx

xmlnamespaces:
    downloadDir: /home/nonroot/download-ns
    importDir: /home/nonroot/import-ns
    
logging:
    level: INFO
    appenders:
      - type: file
        archive: false
        currentLogFilename: /home/nonroot/logs/vocab.log
        maxFileSize: 20MB
        archive: false

server:
  requestLog:
    appenders:
      - type: file
        archive: false
        currentLogFilename: /home/nonroot/logs/vocab-request.log
        maxFileSize: 20MB
        archive: false

views:
    freemarker:
        template_exception_handler: rethrow
        output_encoding: utf-8
        incompatible_improvements: 2.3.27   
